spring.application.name=bff-agendador

usuario.url=http://localhost:8080
agendador-tarefas.url=http://localhost:8081
notificacao.url=http://localhost:8082

cron.horario= 0 0/5 * * * ?

usuario.email=admin@admin.com
usuario.senha=admin

server.port=8083

# Allow bean definition overriding to resolve conflicts between auto-configurations
spring.main.allow-bean-definition-overriding=true
