spring.application.name=bff-agendador
usuario.url=http://localhost:8080
agendador-tarefas.url=http://localhost:8081
server.port=8083

# Allow bean definition overriding to resolve conflicts between auto-configurations
spring.main.allow-bean-definition-overriding=true
